name: my_app
description: "JPEG-Lite Compression Visualizer"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image: ^4.2.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  intl: ^0.19.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ios/jpeglite_logo.png
    - assets/images/ios/jpeglite_logo@2x.png
    - assets/images/ios/jpeglite_logo@3x.png
    - assets/images/android/drawable-mdpi/
    - assets/images/android/drawable-hdpi/
    - assets/images/android/drawable-xhdpi/
    - assets/images/android/drawable-xxhdpi/
    - assets/images/android/drawable-xxxhdpi/
